export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SELLER_ADMIN = 'SELLER_ADMIN',
  SALES_AGENT = 'SALES_AGENT',
  RETAILER = 'RETAILER'
}

export enum UserStatus {
  PENDING_KYC = 'PENDING_KYC',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED'
}

export enum KycStatus {
  PENDING = 'PENDING',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED'
}

export enum KycDocumentType {
  GSTIN = 'GSTIN',
  PAN = 'PAN',
  UDYAM = 'UDYAM',
  SHOP_ESTABLISHMENT_LICENSE = 'SHOP_ESTABLISHMENT_LICENSE',
  TRADE_LICENSE = 'TRADE_LICENSE'
}

export enum BeatDay {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY'
}

export enum VisitDisposition {
  ORDER_BOOKED = 'ORDER_BOOKED',
  STOCK_FULL = 'STOCK_FULL',
  OWNER_UNAVAILABLE = 'OWNER_UNAVAILABLE',
  STORE_CLOSED = 'STORE_CLOSED',
  PRICE_ISSUE = 'PRICE_ISSUE',
  COMPETITOR_PREFERRED = 'COMPETITOR_PREFERRED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  OTHER = 'OTHER'
}

export enum MasterOrderStatus {
  PLACED = 'PLACED',
  PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum SubOrderStatus {
  RECEIVED = 'RECEIVED',
  ACCEPTED = 'ACCEPTED',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}

export enum SubscriptionTier {
  FREE_LISTING = 'FREE_LISTING',
  STARTER_BEAT = 'STARTER_BEAT',
  GROWTH_BEAT = 'GROWTH_BEAT',
  ENTERPRISE_BEAT = 'ENTERPRISE_BEAT'
}

export const GEOFENCE_CONFIG = {
  DEFAULT_CHECKIN_RADIUS_METERS: 100,
  STRICT_CHECKIN_RADIUS_METERS: 50,
  WARNING_RADIUS_METERS: 150
} as const;

export const GST_RATES = [0, 5, 12, 18, 28] as const;

export enum LeadStage {
  PROSPECT = 'PROSPECT',
  CONTACTED = 'CONTACTED',
  KYC_PENDING = 'KYC_PENDING',
  KYC_VERIFIED = 'KYC_VERIFIED',
  ACTIVE_BUYER = 'ACTIVE_BUYER',
  DORMANT = 'DORMANT'
}

export enum PaymentTerm {
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
  CREDIT_NET_7 = 'CREDIT_NET_7',
  CREDIT_NET_15 = 'CREDIT_NET_15',
  CREDIT_NET_30 = 'CREDIT_NET_30',
  CREDIT_NET_45 = 'CREDIT_NET_45',
  WEEKLY_SETTLEMENT = 'WEEKLY_SETTLEMENT',
  UPI_ONLINE = 'UPI_ONLINE',
  BANK_NEFT = 'BANK_NEFT'
}

export enum CreditLineStatus {
  ACTIVE = 'ACTIVE',
  CREDIT_HOLD = 'CREDIT_HOLD',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REJECTED = 'REJECTED'
}

export enum LedgerEntryType {
  INVOICE = 'INVOICE',
  PAYMENT_VOUCHER = 'PAYMENT_VOUCHER',
  CREDIT_NOTE = 'CREDIT_NOTE'
}

export enum VisitPurpose {
  ROUTINE_BEAT = 'ROUTINE_BEAT',
  ORDER_BOOKING = 'ORDER_BOOKING',
  PAYMENT_COLLECTION = 'PAYMENT_COLLECTION',
  DISPUTE_RESOLUTION = 'DISPUTE_RESOLUTION',
  NEW_STORE_ONBOARDING = 'NEW_STORE_ONBOARDING'
}

export enum PaymentMode {
  CASH = 'CASH',
  UPI = 'UPI',
  CHEQUE = 'CHEQUE',
  NEFT = 'NEFT',
  BANK_TRANSFER = 'BANK_TRANSFER',
  DIRECT_SELLER_UPI = 'DIRECT_SELLER_UPI'
}

export enum FmcgCategory {
  STAPLES_GRAINS = 'Staples & Grains',
  BEVERAGES_DRINKS = 'Beverages & Cold Drinks',
  SNACKS_CONFECTIONERY = 'Snacks & Confectionery',
  PACKAGED_FOOD = 'Packaged & Instant Foods',
  PERSONAL_CARE = 'Personal Care & Hygiene',
  CLEANING_HOUSEHOLD = 'Cleaning & Household',
  DAIRY_BAKERY = 'Dairy & Bakery'
}

