export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  SELLER_ADMIN = 'SELLER_ADMIN',
  SALES_AGENT = 'SALES_AGENT',
  RETAILER = 'RETAILER',
  SUPPLY_BD_AGENT = 'SUPPLY_BD_AGENT'
}

export enum UserStatus {
  PENDING_KYC = 'PENDING_KYC',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  ACTIVE = 'ACTIVE',
  SUSPENDED = 'SUSPENDED'
}

export enum KycStatus {
  PENDING = 'PENDING',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED'
}

export enum StockReservationStatus {
  RESERVED = 'RESERVED',
  COMMITTED = 'COMMITTED',
  RELEASED = 'RELEASED',
  FALLBACK_REROUTED = 'FALLBACK_REROUTED'
}

export const ONBOARDING_COLLISION_METERS = 15.0;

export enum KycDocumentType {
  GSTIN = 'GSTIN',
  PAN = 'PAN',
  UDYAM = 'UDYAM',
  SHOP_ESTABLISHMENT_LICENSE = 'SHOP_ESTABLISHMENT_LICENSE',
  TRADE_LICENSE = 'TRADE_LICENSE'
}

export enum BeatDay {
  MONDAY = 'MONDAY',
  TUESDAY = 'TUESDAY',
  WEDNESDAY = 'WEDNESDAY',
  THURSDAY = 'THURSDAY',
  FRIDAY = 'FRIDAY',
  SATURDAY = 'SATURDAY'
}

export enum VisitDisposition {
  ORDER_BOOKED = 'ORDER_BOOKED',
  STOCK_FULL = 'STOCK_FULL',
  OWNER_UNAVAILABLE = 'OWNER_UNAVAILABLE',
  STORE_CLOSED = 'STORE_CLOSED',
  PRICE_ISSUE = 'PRICE_ISSUE',
  COMPETITOR_PREFERRED = 'COMPETITOR_PREFERRED',
  PAYMENT_PENDING = 'PAYMENT_PENDING',
  OTHER = 'OTHER'
}

export enum MasterOrderStatus {
  PLACED = 'PLACED',
  PARTIALLY_DELIVERED = 'PARTIALLY_DELIVERED',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED'
}

export enum SubOrderStatus {
  RECEIVED = 'RECEIVED',
  ACCEPTED = 'ACCEPTED',
  DISPATCHED = 'DISPATCHED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED'
}

export enum SubscriptionTier {
  FREE_LISTING = 'FREE_LISTING',
  STARTER_BEAT = 'STARTER_BEAT',
  GROWTH_BEAT = 'GROWTH_BEAT',
  ENTERPRISE_BEAT = 'ENTERPRISE_BEAT'
}

export const GEOFENCE_CONFIG = {
  DEFAULT_CHECKIN_RADIUS_METERS: 100,
  STRICT_CHECKIN_RADIUS_METERS: 50,
  WARNING_RADIUS_METERS: 150
} as const;

export const GST_RATES = [0, 5, 12, 18, 28] as const;

export enum LeadStage {
  PROSPECT = 'PROSPECT',
  CONTACTED = 'CONTACTED',
  KYC_PENDING = 'KYC_PENDING',
  KYC_VERIFIED = 'KYC_VERIFIED',
  ACTIVE_BUYER = 'ACTIVE_BUYER',
  DORMANT = 'DORMANT'
}

export enum PaymentTerm {
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
  CREDIT_NET_7 = 'CREDIT_NET_7',
  CREDIT_NET_15 = 'CREDIT_NET_15',
  CREDIT_NET_30 = 'CREDIT_NET_30',
  CREDIT_NET_45 = 'CREDIT_NET_45',
  WEEKLY_SETTLEMENT = 'WEEKLY_SETTLEMENT',
  UPI_ONLINE = 'UPI_ONLINE',
  BANK_NEFT = 'BANK_NEFT'
}

export enum CreditLineStatus {
  ACTIVE = 'ACTIVE',
  CREDIT_HOLD = 'CREDIT_HOLD',
  UNDER_REVIEW = 'UNDER_REVIEW',
  REJECTED = 'REJECTED'
}

export enum LedgerEntryType {
  INVOICE = 'INVOICE',
  PAYMENT_VOUCHER = 'PAYMENT_VOUCHER',
  CREDIT_NOTE = 'CREDIT_NOTE'
}

export enum VisitPurpose {
  ROUTINE_BEAT = 'ROUTINE_BEAT',
  ORDER_BOOKING = 'ORDER_BOOKING',
  PAYMENT_COLLECTION = 'PAYMENT_COLLECTION',
  DISPUTE_RESOLUTION = 'DISPUTE_RESOLUTION',
  NEW_STORE_ONBOARDING = 'NEW_STORE_ONBOARDING'
}

export enum PaymentMode {
  CASH = 'CASH',
  UPI = 'UPI',
  CHEQUE = 'CHEQUE',
  NEFT = 'NEFT',
  BANK_TRANSFER = 'BANK_TRANSFER',
  DIRECT_SELLER_UPI = 'DIRECT_SELLER_UPI'
}

export enum FmcgCategory {
  STAPLES_GRAINS = 'Staples & Grains',
  BEVERAGES_DRINKS = 'Beverages & Cold Drinks',
  SNACKS_CONFECTIONERY = 'Snacks & Confectionery',
  PACKAGED_FOOD = 'Packaged & Instant Foods',
  PERSONAL_CARE = 'Personal Care & Hygiene',
  CLEANING_HOUSEHOLD = 'Cleaning & Household',
  DAIRY_BAKERY = 'Dairy & Bakery'
}

export enum StaffRole {
  BILLING_CLERK = 'BILLING_CLERK',
  DISPATCHER = 'DISPATCHER',
  CASHIER = 'CASHIER',
  SALES_REP = 'SALES_REP',
  WAREHOUSE_MANAGER = 'WAREHOUSE_MANAGER',
  STORE_MANAGER = 'STORE_MANAGER',
  ACCOUNTANT = 'ACCOUNTANT',
  HELPER = 'HELPER',
  OWNER = 'OWNER'
}

export enum UserPermission {
  CAN_CREATE_BILLS = 'CAN_CREATE_BILLS',
  CAN_VIEW_POS_CATALOG = 'CAN_VIEW_POS_CATALOG',
  CAN_SCAN_BARCODES = 'CAN_SCAN_BARCODES',
  CAN_INWARD_STOCK = 'CAN_INWARD_STOCK',
  CAN_VIEW_PROFIT_MARGINS = 'CAN_VIEW_PROFIT_MARGINS',
  CAN_OVERRIDE_DISCOUNTS = 'CAN_OVERRIDE_DISCOUNTS',
  CAN_MANAGE_UDHAR = 'CAN_MANAGE_UDHAR',
  CAN_VIEW_ORDERS = 'CAN_VIEW_ORDERS',
  CAN_PACK_BATCHES = 'CAN_PACK_BATCHES',
  CAN_DISPATCH = 'CAN_DISPATCH',
  CAN_PRINT_LABELS = 'CAN_PRINT_LABELS',
  CAN_VIEW_LEDGERS = 'CAN_VIEW_LEDGERS',
  CAN_EXPORT_ERP = 'CAN_EXPORT_ERP',
  CAN_MANAGE_PDC = 'CAN_MANAGE_PDC',
  CAN_MANAGE_CREDIT_LINES = 'CAN_MANAGE_CREDIT_LINES',
  CAN_MANAGE_PRICING = 'CAN_MANAGE_PRICING',
  CAN_MANAGE_USERS = 'CAN_MANAGE_USERS',
  CAN_VIEW_ANALYTICS = 'CAN_VIEW_ANALYTICS'
}

export enum BatchStatus {
  ACTIVE = 'ACTIVE',
  NEAR_EXPIRY = 'NEAR_EXPIRY',
  EXPIRED = 'EXPIRED',
  EXHAUSTED = 'EXHAUSTED'
}

export enum TradeSchemeType {
  BUY_X_GET_Y_FREE = 'BUY_X_GET_Y_FREE',
  CROSS_BRAND_BUNDLE = 'CROSS_BRAND_BUNDLE',
  HAPPY_HOURS = 'HAPPY_HOURS',
  CASH_DISCOUNT_IMMEDIATE = 'CASH_DISCOUNT_IMMEDIATE',
  TARGET_REBATE = 'TARGET_REBATE'
}

export enum LoyaltyTier {
  BRONZE = 'BRONZE',
  SILVER = 'SILVER',
  GOLD = 'GOLD',
  PLATINUM = 'PLATINUM'
}

export enum PdcStatus {
  RECEIVED = 'RECEIVED',
  DEPOSITED = 'DEPOSITED',
  CLEARED = 'CLEARED',
  BOUNCED = 'BOUNCED',
  CANCELLED = 'CANCELLED'
}

export enum KhataEntryType {
  CREDIT_GIVEN = 'CREDIT_GIVEN',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED'
}

export enum ReturnReason {
  DAMAGED_IN_TRANSIT = 'DAMAGED_IN_TRANSIT',
  EXPIRED = 'EXPIRED',
  PACKAGING_LEAK = 'PACKAGING_LEAK',
  NEAR_EXPIRY_REJECTED = 'NEAR_EXPIRY_REJECTED',
  QUALITY_ISSUE = 'QUALITY_ISSUE'
}

export enum AuditAction {
  PRICE_MODIFIED = 'PRICE_MODIFIED',
  CREDIT_LIMIT_CHANGED = 'CREDIT_LIMIT_CHANGED',
  CREDIT_HOLD_TOGGLED = 'CREDIT_HOLD_TOGGLED',
  ORDER_CANCELLED = 'ORDER_CANCELLED',
  SCHEME_CREATED = 'SCHEME_CREATED',
  MANUAL_LEDGER_ENTRY = 'MANUAL_LEDGER_ENTRY'
}

export enum PosPaymentMode {
  CASH = 'CASH',
  UPI = 'UPI',
  KHATA = 'KHATA',
  SPLIT = 'SPLIT'
}

export enum KhataCustomerStatus {
  REGULAR = 'REGULAR',
  OVERDUE = 'OVERDUE',
  BLOCKED = 'BLOCKED'
}

export enum ThermalPrinterType {
  BLUETOOTH_ESC_POS = 'BLUETOOTH_ESC_POS',
  USB_ESC_POS = 'USB_ESC_POS',
  BROWSER_PRINT = 'BROWSER_PRINT'
}

export enum PlatformRiskLevel {
  LOW = 'LOW',
  MODERATE = 'MODERATE',
  HIGH = 'HIGH',
  CRITICAL_NPA = 'CRITICAL_NPA'
}

export enum StockMovementType {
  B2B_DELIVERY_INWARD = 'B2B_DELIVERY_INWARD',
  MANUAL_ADD = 'MANUAL_ADD',
  POS_SALE = 'POS_SALE',
  SPOILAGE_BURST = 'SPOILAGE_BURST',
  RTV_RETURN = 'RTV_RETURN',
  STOCK_ADJUSTMENT = 'STOCK_ADJUSTMENT'
}
